### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ZZ30NN** [I-Skid/web-stealer#10]
im having the same issue as a few other ppl, I'm brand new to coding so idk how to fix but it cant find a directory for /home/runner/main.py is there any way you could help me out
![image_2023-11-28_033638607](https://github.com/I-Skid/web-stealer/assets/152273913/fde84fa7-91d3-45d4-b40b-3aa04a9353f9)

**Comment by ZZ30NN** [comment]
ive foune the right directory for main.py but dontk now where to replace

**Comment by ZZ30NN** [comment]
I've found the correct directory for 'main.py' but don;t know where to enter it.

**Comment by ZZ30NN** [comment]
I've somewhat fixed it to where I don't get the error, I think it was referring to the main.py in replit. Im now having a different issue where when I run it, nothing generates. The box where the website would be is simply blank.
![image](https://github.com/I-Skid/web-stealer/assets/152273913/f17116a1-d686-4748-9416-9c488ccc004c)

**Comment by I-Skid** [comment]
replit is ass now
